/** All customer-facing strings of the bonus feature (BONUS_MODULE_SPEC_RHEMITO.md §7). */
export const BONUS_COPY = {
  blocked: "You're not qualified to get bonus. Please contact support for more information.",
  contactSupport: "Contact support",
  pill: (amount: string) => `You have ${amount} bonus credit.`,
  pillCta: "Create a transaction",
  pillCtaSuffix: "to use it.",
  pillExpiring: (amount: string, days: number) => `${amount} expires in ${days} day${days === 1 ? "" : "s"}.`,
  pillExpiringToday: (amount: string) => `${amount} expires today.`,
  howEarned: "How you earned it",
  view: "View",
  earnedLeft: (earned: string, left: string) => `Earned ${earned} · ${left} left`,
  allFrom: (source: string) => `All earned from ${source}.`,
  outstanding: (amount: string) => `${amount} of future bonus will go towards bonus that was removed after a cancelled or refunded transfer.`,
  tilesEarnedSub: (n: number) => `From ${n} bonus${n === 1 ? "" : "es"}`,
  allSources: "All sources",
  sourceFilter: "Source",
  sourceFilterShowing: (source: string) => `Showing ${source} only`,
  clearFilter: "Show all",
  empty: "No bonuses yet. See ways to earn below.",
  loadError: "We couldn't load your bonus credit. Please try again.",
  tryAgain: "Try again",
  waysToEarn: "Ways to earn",
  waysToEarnSub: "Live offers you can earn bonus credit from.",
  ends: (date: string) => `Ends ${date}`,
  useTitle: "Use your bonus",
  available: (amount: string) => `${amount} available`,
  includes: (parts: string[]) => `Includes ${parts.join(" and ")}`,
  payLess: "Pay less",
  payLessSub: (credit: string, rest?: string) => `Save ${credit} now${rest ? `. ${rest} will stay in your bonus credit.` : ""}`,
  sendMore: "Send more",
  sendMoreSub: (extra: string) => `Recipient gets ${extra} more`,
  dontUse: "Don't use bonus",
  expiryNote: (amount: string, date: string) => `${amount} of this expires on ${date} – it's used first.`,
  toastPayLess: (credit: string) => ({ title: `${credit} bonus applied`, description: `You'll pay ${credit} less.` }),
  toastSendMore: (credit: string) => ({ title: `${credit} bonus added`, description: "Your recipient will get more." }),
  changedTitle: "Your bonus balance has changed",
  changed: "Your bonus balance has changed. Please review your transfer.",
  summaryPayLess: "Bonus credit",
  summarySendMore: "Bonus credit (to recipient)",
} as const;
